export global TextPadPalette {
    in-out property <color> dark_bg_color: #222;
    in-out property <color> light_bg_color: #fff;

    in-out property <color> component_dark_bg_color: #333;
    in-out property <color> component_light_bg_color: #ebebeb;

    in-out property <color> hover_dark_bg_color: #444;
    in-out property <color> hover_light_bg_color: #d4d4d4;

    in-out property <color> text_dark_color: #ddd;
    in-out property <color> text_light_color: #000;
}

export global TextPadTheme {
    in-out property <bool> is_dark_mode: false;
}