export component RoundButton inherits Rectangle {
    in property <image> image;
    in property <string> text;
    
    in property <bool> is_dark_mode: false;
    
    in-out property <color> hover_light_bg_color: #ddd;
    in-out property <color> hover_dark_bg_color: #444;
    in-out property <color> light_bg_color: #ebebeb;
    in-out property <color> dark_bg_color: #333;

    callback clicked();

    border-radius: 4px;
    animate background {
        duration: 100ms;
    }

    Image {
        width: 100%;
        height: 100%;
        source: image;
        image-fit: contain;
        colorize: is_dark_mode ? light_bg_color : dark_bg_color;
    }
    TouchArea {
        width: 100%;
        height: 100%;

        mouse-cursor: MouseCursor.pointer;

        clicked => {
            clicked()
        }
        moved => {
            if (self.has-hover) {
                parent.background = is_dark_mode ? hover_dark_bg_color : hover_light_bg_color;
            } else {
                parent.background = is_dark_mode ? dark_bg_color : light_bg_color;
            }
        }
    }
}