import { TextPadPalette, TextPadTheme } from "global_data.slint";

export component RoundButton inherits Rectangle {
    in property <image> image;
    in property <string> description : "";

    callback clicked();

    border-radius: 4px;
    animate background {
        duration: 100ms;
    }

    Image {
        width: 100%;
        height: 100%;
        source: image;
        image-fit: contain;
        colorize: TextPadTheme.is_dark_mode ? TextPadPalette.light_bg_color : TextPadPalette.dark_bg_color;
    }
    Timer {
        interval: 150ms;
        running: true;

        triggered => {
            if (touch-area.has-hover) {
                parent.background = TextPadTheme.is_dark_mode ? TextPadPalette.hover_dark_bg_color : TextPadPalette.hover_light_bg_color;
            } else {
                parent.background = TextPadTheme.is_dark_mode ? TextPadPalette.component_dark_bg_color : TextPadPalette.component_light_bg_color;
            }
        }
    }
    tip := Rectangle {
        property <bool> show-tooltip: touch-area.has-hover && parent.description != "";
        
        property <length> parent-stable-width: parent.width;
        property <length> text-stable-width: desc-text.preferred-width + 5px;
        property <length> text-stable-height: desc-text.preferred-height + 5px;

        visible: show-tooltip;
        width: text-stable-width;
        height: text-stable-height;
        border-radius: 4px;
        background: TextPadTheme.is_dark_mode ? TextPadPalette.component_dark_bg_color : TextPadPalette.component_light_bg_color;
        x: (parent-stable-width - text-stable-width) / 2;
        y: parent.height + 5px;
        
        opacity: show-tooltip ? 1 : 0;
        animate opacity, x, y, width, height {
            duration: 250ms;
            easing: ease-in-out;
        }

        desc-text := Text {
            text: root.description;
            font-size: 14px;
            color: TextPadTheme.is_dark_mode ? TextPadPalette.light_bg_color : TextPadPalette.dark_bg_color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    touch-area := TouchArea {
        width: 100%;
        height: 100%;

        mouse-cursor: MouseCursor.pointer;

        clicked => {
            clicked()
        }
    }
}