export component RoundButton inherits Rectangle {
    in property <image> image;
    in property <string> description : "";
    in property <bool> is_dark_mode: false;
    
    in-out property <color> hover_light_bg_color: #d4d4d4;
    in-out property <color> hover_dark_bg_color: #444;
    in-out property <color> light_bg_color: #ebebeb;
    in-out property <color> dark_bg_color: #333;

    callback clicked();

    border-radius: 4px;
    animate background {
        duration: 100ms;
    }

    Image {
        width: 100%;
        height: 100%;
        source: image;
        image-fit: contain;
        colorize: is_dark_mode ? light_bg_color : dark_bg_color;
    }
    Timer {
        interval: 150ms;
        running: true;

        triggered => {
            if (touch-area.has-hover) {
                parent.background = is_dark_mode ? hover_dark_bg_color : hover_light_bg_color;
            } else {
                parent.background = is_dark_mode ? dark_bg_color : light_bg_color;
            }
        }
    }
    tip := Rectangle {
        property <bool> show-tooltip: touch-area.has-hover && parent.description != "";
        
        property <length> parent-stable-width: parent.width;
        property <length> text-stable-width: desc-text.preferred-width + 5px;
        property <length> text-stable-height: desc-text.preferred-height + 5px;

        visible: show-tooltip;
        width: text-stable-width;
        height: text-stable-height;
        border-radius: 4px;
        background: is_dark_mode ? dark_bg_color : light_bg_color;
        x: (parent-stable-width - text-stable-width) / 2;
        y: parent.height + 5px;
        
        opacity: show-tooltip ? 1 : 0;
        animate opacity, x, y, width, height {
            duration: 250ms;
            easing: ease-in-out;
        }

        desc-text := Text {
            text: root.description;
            font-size: 14px;
            color: is_dark_mode ? light_bg_color : dark_bg_color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }

    touch-area := TouchArea {
        width: 100%;
        height: 100%;

        mouse-cursor: MouseCursor.pointer;

        clicked => {
            clicked()
        }
    }
}