export component RoundButton inherits Rectangle {
    in-out property <length> size : icon_size;
    in property <image> icon;
    in-out property <length> icon_size : 48px;
    in-out property <string> tooltip_text : "";

    border-radius: size / 2;
    background: #f3f3f3;

    width: size;
    height: size;

    drop-shadow-blur: 4px;
    drop-shadow-color: #888;
    drop-shadow-offset-x: 1px;
    drop-shadow-offset-y: 1px;

    Image {
        source: icon;
        width: icon_size;
        height: icon_size;

        image-fit: contain;
    }

    callback clicked();
    TouchArea {
        width: size;
        height: size;
        clicked => {
            clicked();
        }
    }
}