import { VerticalBox, Button, HorizontalBox, ScrollView, TextEdit, LineEdit } from "std-widgets.slint";
import { RoundButton } from "round_button.slint";

export component TextPad inherits Window {
    width: 800px;
    height: 600px;
    background: is_dark_mode ? dark_bg_color : light_bg_color;
    title: "TextPad - " + current_file;

    in-out property <string> current_file: "Untitled";
    in-out property <[string]> content: [];
    in-out property <bool> is_dark_mode: false;

    property <color> dark_bg_color: #222;
    property <color> light_bg_color: #fff;

    VerticalBox {
        padding: 3px;
        Rectangle {
            property <color> dark_bg_color: #333;
            property <color> light_bg_color: #ebebeb;
            width: 100%;
            height: 28px;
            background: is_dark_mode ? dark_bg_color : light_bg_color;
            HorizontalBox {
                x: 5px;
                padding-top: 0px;
                RoundButton {
                    image: @image-url("../resource/icons/menu-24.png");
                    is_dark_mode <=> root.is_dark_mode;
                    description: "Menu";
                    width: 24px;
                    height: 24px;
                }
                RoundButton {
                    image: @image-url("../resource/icons/add-24.png");
                    is_dark_mode <=> root.is_dark_mode;
                    description: "New File";
                    width: 24px;
                    height: 24px;
                }
                RoundButton {
                    image: @image-url("../resource/icons/open-24.png");
                    is_dark_mode <=> root.is_dark_mode;
                    description: "Open File";
                    width: 24px;
                    height: 24px;
                }
                RoundButton {
                    image: @image-url("../resource/icons/save-24.png");
                    is_dark_mode <=> root.is_dark_mode;
                    description: "Save";
                    width: 24px;
                    height: 24px;
                }
                RoundButton {
                    image: @image-url("../resource/icons/save-as-24.png");
                    is_dark_mode <=> root.is_dark_mode;
                    description: "Save As";
                    width: 24px;
                    height: 24px;
                }
            }
        }
    }
}