import { VerticalBox, Button, HorizontalBox, ScrollView, TextEdit, LineEdit } from "std-widgets.slint";
import { RoundButton } from "round_button.slint";
import { TextPadPalette, TextPadTheme } from "global_data.slint";

export component TextPad inherits Window {
    width: 800px;
    height: 600px;
    background: TextPadTheme.is_dark_mode ? TextPadPalette.dark_bg_color : TextPadPalette.light_bg_color;
    title: "TextPad - " + current_file;
    icon: @image-url("../resource/icons/text-editor-48.png");

    in-out property <string> current_file: "Untitled";
    in-out property <[string]> content: [""];

    in-out property <[string]> opend_files_path: [];
    in-out property <int> current_file_index: -1;

    callback save_file();
    callback open_file();
    callback save_as_file();
    callback new_file();

    VerticalBox {
        padding: 0px;
        Rectangle {
            width: 100%;
            height: 28px;
            background: TextPadTheme.is_dark_mode ? TextPadPalette.component_dark_bg_color : TextPadPalette.component_light_bg_color;
            HorizontalBox {
                x: 5px;
                padding-top: 0px;
                RoundButton {
                    image: @image-url("../resource/icons/menu-24.png");
                    description: "Menu";
                    width: 24px;
                    height: 24px;
                }
                RoundButton {
                    image: @image-url("../resource/icons/add-24.png");
                    description: "New File";
                    width: 24px;
                    height: 24px;
                    clicked => {
                        root.new_file();
                    }
                }
                RoundButton {
                    image: @image-url("../resource/icons/open-24.png");
                    description: "Open File";
                    width: 24px;
                    height: 24px;
                    clicked => {
                        root.open_file();
                    }
                }
                RoundButton {
                    image: @image-url("../resource/icons/save-24.png");
                    description: "Save";
                    width: 24px;
                    height: 24px;
                    clicked => {
                        root.save_file();
                    }
                }
                RoundButton {
                    image: @image-url("../resource/icons/save-as-24.png");
                    description: "Save As";
                    width: 24px;
                    height: 24px;
                    clicked => {
                        root.save_as_file();    
                    }
                }
            }
        }
        ScrollView {
            max-height: parent.height - 28px;
            max-width: parent.width;
            x: 10px;
            VerticalBox {
                width: parent.width - 20px;
                height: parent.height - 28px;
                x: 10px;
                y: 5px;
                for line in content : Text {
                    text: line;
                    font-size: 14px;
                    color: TextPadTheme.is_dark_mode ? TextPadPalette.text_dark_color : TextPadPalette.text_light_color;
                    wrap: no-wrap;
                    font-family: "Consolas, 'Courier New', monospace";
                }
            }
        }
    }
}